<?php
/* Live & Learn Brazil — /contact/ : textos da página e dos e-mails nos quatro idiomas.
   Lido por index.php e send.php. Nada aqui é servido ao navegador. */

declare(strict_types=1);

const CT_WHATSAPP_NUMERO = '+55 11 95439 5027';
const CT_WHATSAPP_LINK   = 'https://wa.me/5511954395027';

const CT_TEXTOS = [
    'en' => [
        'html_lang'      => 'en',
        'titulo'         => 'Contact — Live & Learn Brazil',
        'descricao'      => 'Leave your details and a few lines on what you need. We reply within two working days, in Portuguese, English, Mandarin or Italian.',
        'menu'           => ['Intercultural Due Diligence', 'Innovation Ties', 'Brazilian Portuguese and Communication', 'Destination Services'],
        'menu_aria'      => 'Services',
        'migalha_home'   => 'Home',
        'migalha_aqui'   => 'Contact',
        'rotulo'         => 'CONTACT',
        'h1'             => 'How can we help?',
        'lead'           => 'Leave your details and a few lines on what you need. We reply within two working days, in Portuguese, English, Mandarin or Italian.',
        'nome'           => 'Full name',
        'telefone'       => 'Phone or WhatsApp',
        'email'          => 'Email',
        'mensagem'       => 'What do you need?',
        'mensagem_dica'  => 'A few lines are enough.',
        'obrigatorio'    => '(required)',
        'opcional'       => '(optional)',
        'nota'           => 'We use what you write here only to reply to you.',
        'enviar'         => 'Send',
        'enviando'       => 'Sending…',
        'recebido_rotulo' => 'RECEIVED',
        'recebido_h2'    => 'Thank you. We will reply within two working days.',
        'recebido_p'     => 'A copy of your message has been sent to the email you gave. If nothing arrives, check your spam folder.',
        'voltar'         => 'Back to the home page',
        'erro'           => 'Something went wrong and your message was not sent. Please try again, or reach us on WhatsApp below.',
        'mobile_rotulo'  => 'PREFER MOBILE?',
        'mobile_p'       => 'Write to us on WhatsApp, or scan the WeChat code.',
        'wechat'         => 'WeChat',
        'wechat_alt'     => 'Live & Learn Brazil WeChat QR code',
        'destino_abertura' => 'Request a scope — Destination Services. Services I want to evaluate:',
        'inovacao_abertura' => 'Innovation Ties — initial call. I would like to talk about a partnership project:',
        'conf_assunto'   => 'We have received your message — Live & Learn Brazil',
        'conf_corpo'     => "Thank you, {nome}. We have received your message and will reply within two working days, to this address.\n\nIf you need to add anything in the meantime, just reply to this email.",
    ],
    'pt' => [
        'html_lang'      => 'pt-BR',
        'titulo'         => 'Contato — Live & Learn Brazil',
        'descricao'      => 'Deixe seus dados e algumas linhas sobre o que precisa. Respondemos em até dois dias úteis, em português, inglês, mandarim ou italiano.',
        'menu'           => ['Intercultural Due Diligence', 'Innovation Ties', 'Brazilian Portuguese and Communication', 'Destination Services'],
        'menu_aria'      => 'Serviços',
        'migalha_home'   => 'Início',
        'migalha_aqui'   => 'Contato',
        'rotulo'         => 'CONTATO',
        'h1'             => 'Como podemos ajudar?',
        'lead'           => 'Deixe seus dados e algumas linhas sobre o que precisa. Respondemos em até dois dias úteis, em português, inglês, mandarim ou italiano.',
        'nome'           => 'Nome completo',
        'telefone'       => 'Telefone ou WhatsApp',
        'email'          => 'E-mail',
        'mensagem'       => 'O que você precisa?',
        'mensagem_dica'  => 'Algumas linhas bastam.',
        'obrigatorio'    => '(obrigatório)',
        'opcional'       => '(opcional)',
        'nota'           => 'Usamos o que você escrever aqui apenas para responder.',
        'enviar'         => 'Enviar',
        'enviando'       => 'Enviando…',
        'recebido_rotulo' => 'RECEBIDO',
        'recebido_h2'    => 'Obrigado. Respondemos em até dois dias úteis.',
        'recebido_p'     => 'Uma cópia da sua mensagem foi enviada para o e-mail informado. Se nada chegar, verifique a pasta de spam.',
        'voltar'         => 'Voltar à página inicial',
        'erro'           => 'Algo deu errado e a mensagem não foi enviada. Tente de novo ou fale conosco pelo WhatsApp abaixo.',
        'mobile_rotulo'  => 'PREFERE O CELULAR?',
        'mobile_p'       => 'Escreva pelo WhatsApp ou leia o código do WeChat.',
        'wechat'         => 'WeChat',
        'wechat_alt'     => 'Código QR do WeChat da Live & Learn Brazil',
        'destino_abertura' => 'Pedido de escopo — Destination Services. Serviços que quero avaliar:',
        'inovacao_abertura' => 'Innovation Ties — conversa inicial. Gostaria de falar sobre um projeto de parceria:',
        'conf_assunto'   => 'Recebemos a sua mensagem — Live & Learn Brazil',
        'conf_corpo'     => "Obrigado, {nome}. Recebemos a sua mensagem e respondemos em até dois dias úteis, neste endereço.\n\nSe quiser acrescentar algo enquanto isso, basta responder a este e-mail.",
    ],
    'it' => [
        'html_lang'      => 'it',
        'titulo'         => 'Contatti — Live & Learn Brazil',
        'descricao'      => 'Lasciaci i tuoi dati e qualche riga su ciò di cui hai bisogno. Rispondiamo entro due giorni lavorativi, in portoghese, inglese, mandarino o italiano.',
        'menu'           => ['Intercultural Due Diligence', 'Innovation Ties', 'Brazilian Portuguese and Communication', 'Destination Services'],
        'menu_aria'      => 'Servizi',
        'migalha_home'   => 'Home',
        'migalha_aqui'   => 'Contatti',
        'rotulo'         => 'CONTATTI',
        'h1'             => 'Come possiamo aiutarti?',
        'lead'           => 'Lasciaci i tuoi dati e qualche riga su ciò di cui hai bisogno. Rispondiamo entro due giorni lavorativi, in portoghese, inglese, mandarino o italiano.',
        'nome'           => 'Nome e cognome',
        'telefone'       => 'Telefono o WhatsApp',
        'email'          => 'E-mail',
        'mensagem'       => 'Di cosa hai bisogno?',
        'mensagem_dica'  => 'Bastano poche righe.',
        'obrigatorio'    => '(obbligatorio)',
        'opcional'       => '(facoltativo)',
        'nota'           => 'Usiamo ciò che scrivi qui solo per risponderti.',
        'enviar'         => 'Invia',
        'enviando'       => 'Invio…',
        'recebido_rotulo' => 'RICEVUTO',
        'recebido_h2'    => 'Grazie. Rispondiamo entro due giorni lavorativi.',
        'recebido_p'     => 'Una copia del messaggio è stata inviata all’e-mail indicata. Se non arriva nulla, controlla la cartella spam.',
        'voltar'         => 'Torna alla pagina iniziale',
        'erro'           => 'Qualcosa è andato storto e il messaggio non è stato inviato. Riprova, oppure scrivici su WhatsApp qui sotto.',
        'mobile_rotulo'  => 'PREFERISCI IL CELLULARE?',
        'mobile_p'       => 'Scrivici su WhatsApp o inquadra il codice WeChat.',
        'wechat'         => 'WeChat',
        'wechat_alt'     => 'Codice QR WeChat di Live & Learn Brazil',
        'destino_abertura' => 'Richiesta di preventivo — Destination Services. Servizi che voglio valutare:',
        'inovacao_abertura' => 'Innovation Ties — primo colloquio. Vorrei parlare di un progetto di partenariato:',
        'conf_assunto'   => 'Abbiamo ricevuto il tuo messaggio — Live & Learn Brazil',
        'conf_corpo'     => "Grazie, {nome}. Abbiamo ricevuto il tuo messaggio e risponderemo entro due giorni lavorativi, a questo indirizzo.\n\nSe nel frattempo vuoi aggiungere qualcosa, rispondi pure a questa e-mail.",
    ],
    'zh' => [
        'html_lang'      => 'zh-Hans',
        'titulo'         => '联系我们 — Live & Learn Brazil',
        'descricao'      => '请留下您的联系方式，并简单说明您的需求。我们将在两个工作日内回复，可使用中文、英语、葡萄牙语或意大利语。',
        'menu'           => ['跨文化尽职调查', '巴中创新合作', '巴西葡萄牙语与沟通', '巴西落地服务'],
        'menu_aria'      => '服务',
        'migalha_home'   => '首页',
        'migalha_aqui'   => '联系我们',
        'rotulo'         => '联系我们',
        'h1'             => '我们能为您做什么？',
        'lead'           => '请留下您的联系方式，并简单说明您的需求。我们将在两个工作日内回复，可使用中文、英语、葡萄牙语或意大利语。',
        'nome'           => '姓名',
        'telefone'       => '电话或 WhatsApp',
        'email'          => '电子邮箱',
        'mensagem'       => '您需要什么帮助？',
        'mensagem_dica'  => '简单几句即可。',
        'obrigatorio'    => '（必填）',
        'opcional'       => '（选填）',
        'nota'           => '您在此填写的信息仅用于回复您。',
        'enviar'         => '发送',
        'enviando'       => '发送中…',
        'recebido_rotulo' => '已收到',
        'recebido_h2'    => '感谢您的来信。我们将在两个工作日内回复。',
        'recebido_p'     => '副本已发送至您填写的邮箱。如未收到，请查看垃圾邮件文件夹。',
        'voltar'         => '返回首页',
        'erro'           => '发送失败，信息未能送出。请重试，或通过下方的 WhatsApp 联系我们。',
        'mobile_rotulo'  => '更习惯用手机？',
        'mobile_p'       => '可通过 WhatsApp 联系我们，或扫描微信二维码。',
        'wechat'         => '微信',
        'wechat_alt'     => 'Live & Learn Brazil 微信二维码',
        'destino_abertura' => '落地服务报价申请。我希望评估的服务：',
        'inovacao_abertura' => '巴中创新合作 — 初次通话。我想沟通一个合作项目：',
        'conf_assunto'   => '我们已收到您的信息 — Live & Learn Brazil',
        'conf_corpo'     => "{nome}，您好。我们已收到您的信息，将在两个工作日内回复至此邮箱。\n\n如需补充，直接回复本邮件即可。",
    ],
];

/* Idioma pedido em ?lang= (ou no campo lang do formulário); inglês quando não reconhecido. */
function ct_idioma(string $pedido): string
{
    return isset(CT_TEXTOS[$pedido]) ? $pedido : 'en';
}

/* Caminho da própria página no idioma dado (usado no canonical, no hreflang e no redirecionamento). */
function ct_pagina(string $lang): string
{
    return '/contact/' . ($lang === 'en' ? '' : '?lang=' . $lang);
}
